package com.prime.app.jpa.test;

import com.prime.infra.util.WrapperUtils;


public class RunTarifas extends RunGenericRDMS {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
			// ULTIMA TARIFA VIGENTE
//			findQBE(" SELECT CDMUNICIP,CDTARIFA,CDCATCON,QTFAIXATE,DJVIGENC, VLAGUA,VLESGOTO,CDTCOBR,STBLOQUE " +
//					" FROM CTF01 " +
//					" WHERE STREGIST=0 AND STBLOQUE=0 AND CDMUNICIP=100 AND CDCATCON=1 AND CDTCOBR='1' AND CDTARIFA=4 " +
//					" AND DJVIGENC < 19631 " +
//					" ORDER BY DJVIGENC DESC, CDMUNICIP, CDCATCON, CDTARIFA, QTFAIXATE FETCH FIRST 5 ROW ONLY");

			// descrição da TARIFA
//			findQBE(" SELECT CDTARIFA FROM CTF06 WHERE CDMUNICIP=100");
			
			// descrição da condição ligação
//			findQBE(" SELECT B.CDCOBR, B.CDTCOBR, B.CDSCOBR, C.CDCONDLIG, D.DSCONDLIG " +
//					" FROM PCCG0305 A, CCG03 B, PCTC3503 C, CTC35 D " +
//					" WHERE A.NRRGILIG=52791947 AND A.NRRGILIG=B.NRRGILIG AND A.NRGRUPFAT=B.NRGRUPFAT " +
//					" AND C.CDCOBR=B.CDCOBR AND C.CDTCOBR=B.CDTCOBR AND C.CDSCOBR=B.CDSCOBR " +
//					" AND D.CDCONDLIG= C.CDCONDLIG AND D.CDCOBR=B.CDCOBR AND D.CDSCOBR=B.CDSCOBR " +
//					" AND D.CDTCOBR=B.CDTCOBR");

//			findQBE(" SELECT CDMUNICIP,CDTARIFA,CDCATCON,QTFAIXATE,DJVIGENC,VLAGUA,VLESGOTO " +
//					" FROM CTF01 WHERE STREGIST=0 AND STBLOQUE=0 AND CDMUNICIP=100 AND CDCATCON=1 AND CDTCOBR='0' " +
//					" AND CDTARIFA=4 AND DJVIGENC < 19631 " +
//					" ORDER BY DJVIGENC DESC, CDMUNICIP, CDCATCON, CDTARIFA, QTFAIXATE FETCH FIRST 5 ROW ONLY");
	
//		   findQBE("SELECT CDCATCON FROM PCCG0403 WHERE STREGIST=2 AND NRRGILIG=2720");
//		  findQBE(" SELECT CDMUNICIP,CDTARIFA,CDCATCON,QTFAIXATE,DJVIGENC,VLAGUA,VLESGOTO,CDTCOBR  " +
//		  		  " FROM CTF01 WHERE STREGIST=0 AND STBLOQUE=0 AND CDMUNICIP=98989 AND CDCATCON=1 " +
//		  		  " AND CDTCOBR='0'  AND CDTARIFA=1 AND DJVIGENC  < 19631 ORDER BY DJVIGENC DESC, " +
//		  		  " CDMUNICIP, CDCATCON, CDTARIFA, QTFAIXATE  FETCH FIRST 5 ROW ONLY ");
		  
		  findQBE(" SELECT CDMUNICIP,CDTARIFA,CDCATCON,QTFAIXATE,DJVIGENC,VLAGUA,VLESGOTO,CDTCOBR  " +
		  		"  FROM CTF01 WHERE STREGIST=0 AND STBLOQUE=0 AND CDMUNICIP=100 AND CDCATCON=1 AND CDTCOBR='0'  AND CDTARIFA= 4  AND " +
		  		"  DJVIGENC<= 19631 ORDER BY DJVIGENC DESC, CDMUNICIP, CDCATCON, CDTARIFA, QTFAIXATE  FETCH FIRST 5 ROW ONLY ");
		
	}

}
